name: Verify lockfile matches package.json

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-lockfile:
    name: Verify lockfile matches package.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Verify package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json not found"
            exit 1
          fi
          echo "package-lock.json found, proceeding with install"

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Friendly message on success
        if: success()
        run: echo "package-lock.json matches package.json"
