name: NodeJS with Webpack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack and verify pnpm
        run: |
          set -euo pipefail
          corepack enable
          corepack prepare pnpm@10.17.1 --activate
          # Verify pnpm exists; fail early rather than attempting a global npm install
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm was not created by corepack. Listing common locations for debugging..." >&2
            ls -l /usr/local/bin || true
            ls -l /opt/hostedtoolcache || true
            echo "pnpm not available after corepack prepare; failing to avoid npm global install race conditions." >&2
            exit 1
          fi
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm exec webpack
